export { add } from './src/main/ets/utils/Calc';
export { AbsCamera, CameraState, ICameraListener, ImageData, CameraParameters } from './src/main/ets/AbsCamera';
export { CameraApi } from './src/main/ets/CameraApi';
export { AbsCameraReader,SlotState,WriteHandle } from './src/main/ets/AbsCameraReader';
export { PixelMapFrameProducer } from './src/main/ets/PixelMapFrameProducer'
export { decode } from './src/main/ets/utils/zxing/decode'
export { getPixelMap } from './src/main/ets/utils/zxing/imageUtils'
export { AutoFitXComponent } from './src/main/ets/AutoFitXComponent'

//camera-worker demo
export { CameraService } from './src/main/ets/CameraService';